"""
	Corrects errors in transformer phase shifts applied to buses

"""



CorrectBusData = 'AllMappedBusDataIter2.txt' # bus data generated by change3winderDatav14 in the '3 winder substitution' folder
old2winderRawFile = 'FinalRAW03272018Old.raw' # Complete raw file generated by addtfSpecialCases
new2winderRawFile = 'FinalRAW03272018.raw' # raw file with corrected phase angles, generated here

DoubtAngleDict = {}
CorrectAngleDict = {}
CorrectAngleLines = {}
newRawLines = []

with open(CorrectBusData,'r') as f:
	filecontent = f.read()
	fileLines = filecontent.split('\n')
	originalAngleChangeLines = list(fileLines)
	for line in fileLines:
		if line == '':
			continue

		words = line.split(',')
		Bus = words[0].strip()
		angle = words[8].strip()
		CorrectAngleLines[Bus] = line
		CorrectAngleDict[Bus] = angle


with open(old2winderRawFile, 'r') as f:
	filecontent = f.read()
	fileLines = filecontent.split('\n')
	for line in fileLines:
		# append header lines
		if ('PSS' in line) or ('COMED' in line) or ('DYNAMICS' in line):
			newRawLines.append(line)
			continue
		
		# end of bus data
		if 'END OF BUS DATA' in line:
			break


		words = line.split(',')
		if len(words) <2:
			continue
		Bus = words[0].strip()
		angle = words[8].strip()

		if Bus in CorrectAngleDict.keys(): # Bus present in CorrectBusData, substitute it with correct bus data
			newRawLines.append(CorrectAngleLines[Bus])
		else: # bus not present in CorrectBusData, just add it
			newRawLines.append(line)

busEndIndex = fileLines.index('0 / END OF BUS DATA, BEGIN LOAD DATA')

# add these two bus lines, for some reason they were missing
newRawLines.append("243083,'05CAMPSS    ', 138.0000,1, 205,1251,   1,1.01145, -55.0773")
newRawLines.append("658082,'MPSSE  7    ', 115.0000,1, 652,1624, 658,1.02055, -45.2697")


# append the remaining data in the old raw file
for i in range(busEndIndex, len(fileLines)):
	line = fileLines[i]
	newRawLines.append(line)

with open(new2winderRawFile,'w') as f:
	"""
	f.write('0,   100.00, 33, 1, 1, 60.00     / PSS(R)E-33.3    TUE, DEC 13 2016  22:08')
	f.write('\n')
	f.write('COMED 2018,  HLS18V1, N18S OUTSIDE AND 18 INTCHNG')
	f.write('\n')
	f.write('DYNAMICS REVSION 01')
	f.write('\n')
	"""
	for line in newRawLines:
		f.write(line)
		f.write('\n')